name: TFG
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - arrow==1.4.0
      - async-timeout==5.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - charset-normalizer==3.4.4
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - debugpy==1.8.17
      - dill==0.3.8
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - hf-xet==1.2.0
      - huggingface-hub==0.35.3
      - idna==3.11
      - ipykernel==7.0.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyterlab==4.4.9
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nltk==3.9.2
      - notebook==7.4.7
      - numpy==2.2.6
      - overrides==7.7.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - psutil==7.1.1
      - pyarrow==21.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-crfsuite==0.9.11
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.10.23
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - seqeval==1.2.2
      - sklearn-crfsuite==0.5.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.1+cu128
      - torchaudio==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yarl==1.22.0
